### ISSUE TITLE
Seeking to play HDHR-US (old hardware) on Kodi

### ISSUE THREAD

**Issue by sengsational** [micahg/hdhrlive#1]
I blindly bought a Pi 3 and added the current Kodi release (LibreELEC) without checking to see if my HDHomerun was supported.  I have two of the original HDHomerun boxes [Both "HDHR-US" (the original HD Homerun), and "HDHR3-US" seem to be abandoned by the current add-on].

I have a Windows XP machine that does my scheduled recordings, but want live TV through Kodi.  Is it likely that I could install this tool and have it tune live TV using the Kodi interface on the Pi?

**Comment by micahg** [comment]
You could, but you'd need to be familiar with nodejs.

This is mostly a personal project and I'm not really able to provide support.
